CREATE TABLE gender (
  gender_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(10) NOT NULL UNIQUE,
  name varchar(50) NOT NULL,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT gender_code_format CHECK (code = upper(code))
);

CREATE TABLE state (
  state_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_name varchar(150) NOT NULL,
  nationality_id integer,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT state_name_unique UNIQUE (state_name)
);

CREATE TABLE district (
  district_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district_code char(4) NOT NULL UNIQUE,
  district_name varchar(150) NOT NULL,
  state_id integer NOT NULL REFERENCES state(state_id),
  active boolean NOT NULL DEFAULT true,
  boundary geometry(MultiPolygon, 4326),
  centroid geometry(Point, 4326),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT district_code_format CHECK (btrim(district_code) ~ '^[0-9]{4}$'),
  CONSTRAINT district_name_per_state_unique UNIQUE (state_id, district_name)
);

CREATE TABLE unit_type (
  unit_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_type_name varchar(120) NOT NULL UNIQUE,
  operational_level varchar(30) NOT NULL,
  hierarchy integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE police_unit (
  unit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_code char(4) NOT NULL UNIQUE,
  unit_name varchar(200) NOT NULL,
  type_id integer NOT NULL REFERENCES unit_type(unit_type_id),
  parent_unit_id integer REFERENCES police_unit(unit_id),
  nationality_id integer,
  state_id integer NOT NULL REFERENCES state(state_id),
  district_id integer REFERENCES district(district_id),
  active boolean NOT NULL DEFAULT true,
  jurisdiction geometry(MultiPolygon, 4326),
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  location geometry(Point, 4326),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT police_unit_code_format CHECK (btrim(unit_code) ~ '^[0-9]{4}$'),
  CONSTRAINT police_unit_coordinate_pair CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)),
  CONSTRAINT police_unit_latitude_range CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT police_unit_longitude_range CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE police_rank (
  rank_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rank_name varchar(100) NOT NULL UNIQUE,
  hierarchy integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE designation (
  designation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  designation_name varchar(150) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE employee (
  employee_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district_id integer REFERENCES district(district_id),
  unit_id integer REFERENCES police_unit(unit_id),
  rank_id integer REFERENCES police_rank(rank_id),
  designation_id integer REFERENCES designation(designation_id),
  kgid varchar(50) UNIQUE,
  first_name varchar(150),
  employee_dob date,
  gender_id smallint REFERENCES gender(gender_id),
  blood_group_id integer,
  physically_challenged boolean,
  appointment_date date,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE case_category (
  case_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_code char(1) NOT NULL UNIQUE,
  lookup_value varchar(50) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE gravity_offence (
  gravity_offence_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lookup_value varchar(100) NOT NULL UNIQUE,
  severity_weight numeric(5, 2) NOT NULL DEFAULT 1,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT gravity_offence_weight_valid CHECK (severity_weight >= 0)
);

CREATE TABLE case_status (
  case_status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_status_name varchar(100) NOT NULL UNIQUE,
  is_terminal boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE court (
  court_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_name varchar(250) NOT NULL,
  district_id integer REFERENCES district(district_id),
  state_id integer REFERENCES state(state_id),
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT court_name_location_unique UNIQUE NULLS NOT DISTINCT (court_name, district_id, state_id)
);

CREATE TABLE occupation_master (
  occupation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occupation_name varchar(150) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE religion_master (
  religion_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  religion_name varchar(150) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  source_compatibility_only boolean NOT NULL DEFAULT true
);

CREATE TABLE caste_master (
  caste_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caste_name varchar(150) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  source_compatibility_only boolean NOT NULL DEFAULT true
);

CREATE TABLE act (
  act_code varchar(30) PRIMARY KEY,
  act_description text,
  short_name varchar(100),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE legal_section (
  act_code varchar(30) NOT NULL REFERENCES act(act_code),
  section_code varchar(50) NOT NULL,
  section_description text,
  active boolean NOT NULL DEFAULT true,
  PRIMARY KEY (act_code, section_code)
);

CREATE TABLE crime_head (
  crime_head_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crime_group_name varchar(200) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE crime_sub_head (
  crime_sub_head_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crime_head_id integer NOT NULL REFERENCES crime_head(crime_head_id),
  crime_head_name varchar(200) NOT NULL,
  seq_id integer NOT NULL DEFAULT 1,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT crime_sub_head_sequence_unique UNIQUE (crime_head_id, seq_id),
  CONSTRAINT crime_sub_head_name_unique UNIQUE (crime_head_id, crime_head_name)
);

CREATE TABLE crime_head_act_section (
  crime_head_id integer NOT NULL REFERENCES crime_head(crime_head_id),
  act_code varchar(30) NOT NULL,
  section_code varchar(50) NOT NULL,
  PRIMARY KEY (crime_head_id, act_code, section_code),
  FOREIGN KEY (act_code, section_code) REFERENCES legal_section(act_code, section_code)
);
