CREATE TABLE crime_number_counter (
  case_category_id integer NOT NULL REFERENCES case_category(case_category_id),
  district_id integer NOT NULL REFERENCES district(district_id),
  police_station_id integer NOT NULL REFERENCES police_unit(unit_id),
  case_year smallint NOT NULL CHECK (case_year BETWEEN 2000 AND 9999),
  last_serial integer NOT NULL DEFAULT 0 CHECK (last_serial BETWEEN 0 AND 99999),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (case_category_id, district_id, police_station_id, case_year)
);

CREATE TABLE case_master (
  case_master_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crime_no varchar(30) NOT NULL UNIQUE,
  case_no varchar(20) NOT NULL,
  case_year smallint NOT NULL,
  running_serial integer NOT NULL,
  crime_registered_at timestamptz NOT NULL,
  police_person_id bigint REFERENCES employee(employee_id),
  police_station_id integer NOT NULL REFERENCES police_unit(unit_id),
  case_category_id integer NOT NULL REFERENCES case_category(case_category_id),
  gravity_offence_id integer REFERENCES gravity_offence(gravity_offence_id),
  crime_major_head_id integer REFERENCES crime_head(crime_head_id),
  crime_minor_head_id integer REFERENCES crime_sub_head(crime_sub_head_id),
  case_status_id integer REFERENCES case_status(case_status_id),
  court_id bigint REFERENCES court(court_id),
  incident_from_at timestamptz,
  incident_to_at timestamptz,
  info_received_ps_at timestamptz,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  incident_location geometry(Point, 4326),
  brief_facts text,
  source_system varchar(100),
  source_record_id varchar(150),
  data_classification varchar(30) NOT NULL DEFAULT 'RESTRICTED',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT case_master_crime_no_format CHECK (crime_no ~ '^[0-9]{18}$'),
  CONSTRAINT case_master_case_no_format CHECK (case_no ~ '^[0-9]{9}$'),
  CONSTRAINT case_master_year_valid CHECK (case_year BETWEEN 2000 AND 9999),
  CONSTRAINT case_master_running_serial_valid CHECK (running_serial BETWEEN 1 AND 99999),
  CONSTRAINT case_master_incident_window_valid CHECK (incident_to_at IS NULL OR incident_from_at IS NULL OR incident_to_at >= incident_from_at),
  CONSTRAINT case_master_registration_window_valid CHECK (info_received_ps_at IS NULL OR crime_registered_at >= info_received_ps_at),
  CONSTRAINT case_master_coordinate_pair CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)),
  CONSTRAINT case_master_latitude_range CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT case_master_longitude_range CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  CONSTRAINT case_master_classification_valid CHECK (data_classification IN ('PUBLIC', 'INTERNAL', 'RESTRICTED', 'CONFIDENTIAL')),
  CONSTRAINT case_master_station_serial_unique UNIQUE (police_station_id, case_category_id, case_year, running_serial)
);

CREATE TABLE complainant_details (
  complainant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  canonical_person_id uuid,
  complainant_name varchar(200),
  age_year smallint,
  occupation_id integer REFERENCES occupation_master(occupation_id),
  religion_id integer REFERENCES religion_master(religion_id),
  caste_id integer REFERENCES caste_master(caste_id),
  gender_id smallint REFERENCES gender(gender_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT complainant_age_valid CHECK (age_year IS NULL OR age_year BETWEEN 0 AND 120)
);

CREATE TABLE victim (
  victim_master_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  canonical_person_id uuid,
  victim_name varchar(200),
  age_year smallint,
  gender_id smallint REFERENCES gender(gender_id),
  victim_police boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT victim_age_valid CHECK (age_year IS NULL OR age_year BETWEEN 0 AND 120)
);

CREATE TABLE accused (
  accused_master_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  canonical_person_id uuid,
  accused_name varchar(200),
  age_year smallint,
  gender_id smallint REFERENCES gender(gender_id),
  accused_sequence varchar(20),
  accused_status varchar(50),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT accused_age_valid CHECK (age_year IS NULL OR age_year BETWEEN 0 AND 120),
  CONSTRAINT accused_case_sequence_unique UNIQUE NULLS NOT DISTINCT (case_master_id, accused_sequence)
);

CREATE TABLE act_section_association (
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  act_code varchar(30) NOT NULL,
  section_code varchar(50) NOT NULL,
  act_order_id integer NOT NULL DEFAULT 1,
  section_order_id integer NOT NULL DEFAULT 1,
  PRIMARY KEY (case_master_id, act_code, section_code),
  FOREIGN KEY (act_code, section_code) REFERENCES legal_section(act_code, section_code),
  CONSTRAINT act_section_order_valid CHECK (act_order_id > 0 AND section_order_id > 0)
);

CREATE TABLE arrest_surrender (
  arrest_surrender_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  arrest_surrender_type varchar(30) NOT NULL,
  arrest_surrender_at timestamptz,
  state_id integer REFERENCES state(state_id),
  district_id integer REFERENCES district(district_id),
  police_station_id integer REFERENCES police_unit(unit_id),
  io_id bigint REFERENCES employee(employee_id),
  court_id bigint REFERENCES court(court_id),
  is_primary_accused boolean NOT NULL DEFAULT false,
  is_complainant_accused boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arrest_surrender_type_valid CHECK (arrest_surrender_type IN ('ARREST', 'SURRENDER', 'NOTICE', 'OTHER'))
);

CREATE TABLE arrest_surrender_accused (
  arrest_surrender_id bigint NOT NULL REFERENCES arrest_surrender(arrest_surrender_id) ON DELETE CASCADE,
  accused_master_id bigint NOT NULL REFERENCES accused(accused_master_id) ON DELETE CASCADE,
  PRIMARY KEY (arrest_surrender_id, accused_master_id)
);

CREATE TABLE chargesheet_details (
  cs_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  chargesheet_at timestamptz,
  report_type char(1) NOT NULL,
  police_person_id bigint REFERENCES employee(employee_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chargesheet_report_type_valid CHECK (report_type IN ('A', 'B', 'C'))
);

CREATE TABLE case_status_history (
  case_status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  previous_status_id integer REFERENCES case_status(case_status_id),
  new_status_id integer REFERENCES case_status(case_status_id),
  changed_at timestamptz NOT NULL DEFAULT now(),
  changed_by_employee_id bigint REFERENCES employee(employee_id),
  reason text,
  CONSTRAINT case_status_history_change_valid CHECK (previous_status_id IS DISTINCT FROM new_status_id)
);
