CREATE TABLE person (
  person_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name varchar(200),
  normalized_name varchar(200),
  date_of_birth date,
  estimated_birth_year smallint,
  gender_id smallint REFERENCES gender(gender_id),
  mobile_hash varchar(128),
  government_id_hash varchar(128),
  address_hash varchar(128),
  identity_confidence numeric(5, 4) NOT NULL DEFAULT 0.5000,
  verification_status varchar(30) NOT NULL DEFAULT 'UNVERIFIED',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT person_birth_year_valid CHECK (estimated_birth_year IS NULL OR estimated_birth_year BETWEEN 1900 AND 9999),
  CONSTRAINT person_confidence_valid CHECK (identity_confidence BETWEEN 0 AND 1),
  CONSTRAINT person_verification_status_valid CHECK (verification_status IN ('UNVERIFIED', 'SUGGESTED', 'VERIFIED', 'REJECTED'))
);

CREATE TABLE person_alias (
  person_alias_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id uuid NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
  alias_name varchar(200) NOT NULL,
  normalized_alias varchar(200) NOT NULL,
  source_case_id bigint REFERENCES case_master(case_master_id) ON DELETE SET NULL,
  confidence numeric(5, 4) NOT NULL DEFAULT 0.5000,
  CONSTRAINT person_alias_confidence_valid CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT person_alias_unique UNIQUE (person_id, normalized_alias)
);

CREATE TABLE case_person_role (
  case_person_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  person_id uuid NOT NULL REFERENCES person(person_id),
  role_type varchar(30) NOT NULL,
  source_table varchar(50),
  source_record_id varchar(100),
  confidence numeric(5, 4) NOT NULL DEFAULT 0.5000,
  is_verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT case_person_role_type_valid CHECK (role_type IN ('ACCUSED', 'VICTIM', 'COMPLAINANT', 'WITNESS', 'PERSON_OF_INTEREST', 'ARRESTED_PERSON', 'ASSOCIATE')),
  CONSTRAINT case_person_role_confidence_valid CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT case_person_role_source_unique UNIQUE NULLS NOT DISTINCT (case_master_id, person_id, role_type, source_table, source_record_id)
);

CREATE TABLE person_identity_match (
  identity_match_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_person_id uuid NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
  candidate_person_id uuid NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
  name_similarity numeric(5, 4),
  dob_similarity numeric(5, 4),
  address_similarity numeric(5, 4),
  case_overlap_score numeric(5, 4),
  overall_confidence numeric(5, 4) NOT NULL,
  decision varchar(30) NOT NULL DEFAULT 'PENDING_REVIEW',
  reviewed_by uuid,
  reviewed_at timestamptz,
  explanation jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT person_identity_match_distinct CHECK (source_person_id <> candidate_person_id),
  CONSTRAINT person_identity_match_score_valid CHECK (overall_confidence BETWEEN 0 AND 1),
  CONSTRAINT person_identity_match_decision_valid CHECK (decision IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'MERGED')),
  CONSTRAINT person_identity_match_pair_unique UNIQUE (source_person_id, candidate_person_id)
);

CREATE TABLE location (
  location_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  location_type varchar(50) NOT NULL,
  address_text text,
  pincode varchar(10),
  district_id integer REFERENCES district(district_id),
  police_station_id integer REFERENCES police_unit(unit_id),
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  geometry geometry(Point, 4326),
  geohash varchar(20),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT location_coordinate_pair CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)),
  CONSTRAINT location_latitude_range CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT location_longitude_range CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE case_location (
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  location_id uuid NOT NULL REFERENCES location(location_id),
  relationship_type varchar(50) NOT NULL,
  confidence numeric(5, 4) NOT NULL DEFAULT 0.5000,
  PRIMARY KEY (case_master_id, location_id, relationship_type),
  CONSTRAINT case_location_relationship_type_valid CHECK (relationship_type IN ('INCIDENT_LOCATION', 'LAST_SEEN_LOCATION', 'ARREST_LOCATION', 'RECOVERED_PROPERTY_LOCATION', 'SUSPECT_ADDRESS', 'VICTIM_ADDRESS')),
  CONSTRAINT case_location_confidence_valid CHECK (confidence BETWEEN 0 AND 1)
);

CREATE TABLE vehicle (
  vehicle_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_hash varchar(128) UNIQUE,
  vehicle_type varchar(100),
  descriptor varchar(200),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE case_vehicle (
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  vehicle_id uuid NOT NULL REFERENCES vehicle(vehicle_id),
  relationship_type varchar(50) NOT NULL DEFAULT 'USED_IN_CASE',
  confidence numeric(5, 4) NOT NULL DEFAULT 0.5000,
  PRIMARY KEY (case_master_id, vehicle_id, relationship_type),
  CONSTRAINT case_vehicle_confidence_valid CHECK (confidence BETWEEN 0 AND 1)
);

CREATE TABLE modus_operandi (
  mo_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  entry_method varchar(100),
  weapon_type varchar(100),
  target_type varchar(100),
  vehicle_used varchar(100),
  time_pattern varchar(100),
  victim_selection_pattern varchar(150),
  communication_method varchar(150),
  escape_method varchar(150),
  property_targeted varchar(150),
  mo_text text,
  extracted_features jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric(5, 4) NOT NULL DEFAULT 0.5000,
  verification_status varchar(30) NOT NULL DEFAULT 'UNVERIFIED',
  verified_by uuid,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT modus_operandi_confidence_valid CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT modus_operandi_verification_status_valid CHECK (verification_status IN ('UNVERIFIED', 'SUGGESTED', 'VERIFIED', 'REJECTED'))
);

ALTER TABLE complainant_details
  ADD CONSTRAINT complainant_details_canonical_person_fk
  FOREIGN KEY (canonical_person_id) REFERENCES person(person_id);

ALTER TABLE victim
  ADD CONSTRAINT victim_canonical_person_fk
  FOREIGN KEY (canonical_person_id) REFERENCES person(person_id);

ALTER TABLE accused
  ADD CONSTRAINT accused_canonical_person_fk
  FOREIGN KEY (canonical_person_id) REFERENCES person(person_id);
