CREATE TABLE district_socioeconomic_indicator (
  indicator_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district_id integer NOT NULL REFERENCES district(district_id),
  period_start date NOT NULL,
  period_end date NOT NULL,
  population bigint,
  population_density numeric,
  urbanization_rate numeric,
  literacy_rate numeric,
  unemployment_rate numeric,
  poverty_rate numeric,
  police_presence numeric,
  street_light_coverage numeric,
  public_transport_access numeric,
  source_name varchar(200) NOT NULL DEFAULT 'Synthetic KAVACH demo',
  is_synthetic boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT district_indicator_period_valid CHECK (period_end >= period_start),
  CONSTRAINT district_indicator_population_valid CHECK (population IS NULL OR population >= 0),
  CONSTRAINT district_indicator_unique UNIQUE (district_id, period_start, period_end, source_name)
);

CREATE TABLE model_version (
  model_version_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_name varchar(100) NOT NULL,
  model_type varchar(100) NOT NULL,
  version varchar(50) NOT NULL,
  feature_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  training_period jsonb NOT NULL DEFAULT '{}'::jsonb,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT model_version_unique UNIQUE (model_name, version)
);

CREATE TABLE model_run (
  model_run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_version_id uuid REFERENCES model_version(model_version_id),
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  status varchar(30) NOT NULL DEFAULT 'RUNNING',
  input_filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  record_count integer,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  CONSTRAINT model_run_status_valid CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEGRADED')),
  CONSTRAINT model_run_completion_valid CHECK (completed_at IS NULL OR completed_at >= started_at),
  CONSTRAINT model_run_record_count_valid CHECK (record_count IS NULL OR record_count >= 0)
);

CREATE TABLE alert (
  alert_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_type varchar(50) NOT NULL,
  severity varchar(20) NOT NULL,
  title varchar(250) NOT NULL,
  description text NOT NULL,
  district_id integer REFERENCES district(district_id),
  police_station_id integer REFERENCES police_unit(unit_id),
  crime_head_id integer REFERENCES crime_head(crime_head_id),
  status varchar(30) NOT NULL DEFAULT 'OPEN',
  detected_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by uuid,
  assigned_to uuid,
  model_run_id uuid REFERENCES model_run(model_run_id),
  deduplication_key varchar(250) NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alert_severity_valid CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  CONSTRAINT alert_status_valid CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED')),
  CONSTRAINT alert_deduplication_key_unique UNIQUE (deduplication_key)
);

CREATE TABLE alert_evidence (
  alert_evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id uuid NOT NULL REFERENCES alert(alert_id) ON DELETE CASCADE,
  case_master_id bigint REFERENCES case_master(case_master_id) ON DELETE SET NULL,
  metric_name varchar(100) NOT NULL,
  metric_value numeric,
  baseline_value numeric,
  difference_percentage numeric,
  evidence_text text NOT NULL
);

CREATE TABLE prediction (
  prediction_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_run_id uuid REFERENCES model_run(model_run_id),
  prediction_type varchar(50) NOT NULL,
  district_id integer REFERENCES district(district_id),
  police_station_id integer REFERENCES police_unit(unit_id),
  crime_head_id integer REFERENCES crime_head(crime_head_id),
  forecast_start timestamptz NOT NULL,
  forecast_end timestamptz NOT NULL,
  risk_score numeric(6, 3) NOT NULL,
  risk_band varchar(20) NOT NULL,
  confidence numeric(5, 4) NOT NULL,
  explanation text NOT NULL,
  data_freshness_at timestamptz NOT NULL,
  human_review_status varchar(30) NOT NULL DEFAULT 'PENDING_REVIEW',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT prediction_window_valid CHECK (forecast_end >= forecast_start),
  CONSTRAINT prediction_risk_score_valid CHECK (risk_score BETWEEN 0 AND 100),
  CONSTRAINT prediction_confidence_valid CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT prediction_risk_band_valid CHECK (risk_band IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')),
  CONSTRAINT prediction_review_status_valid CHECK (human_review_status IN ('PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE prediction_factor (
  prediction_factor_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prediction_id uuid NOT NULL REFERENCES prediction(prediction_id) ON DELETE CASCADE,
  factor_name varchar(150) NOT NULL,
  factor_value numeric,
  contribution numeric NOT NULL,
  direction varchar(20) NOT NULL,
  explanation text NOT NULL,
  CONSTRAINT prediction_factor_direction_valid CHECK (direction IN ('INCREASE', 'DECREASE', 'NEUTRAL'))
);

CREATE TABLE data_import (
  import_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  filename varchar(255) NOT NULL,
  source_type varchar(50) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'UPLOADED',
  total_rows integer NOT NULL DEFAULT 0,
  accepted_rows integer NOT NULL DEFAULT 0,
  rejected_rows integer NOT NULL DEFAULT 0,
  duplicate_rows integer NOT NULL DEFAULT 0,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  uploaded_by uuid,
  mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT data_import_status_valid CHECK (status IN ('UPLOADED', 'VALIDATING', 'VALIDATED', 'COMMITTED', 'FAILED', 'CANCELLED')),
  CONSTRAINT data_import_counts_valid CHECK (total_rows >= 0 AND accepted_rows >= 0 AND rejected_rows >= 0 AND duplicate_rows >= 0),
  CONSTRAINT data_import_completion_valid CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE data_import_error (
  import_error_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id uuid NOT NULL REFERENCES data_import(import_id) ON DELETE CASCADE,
  row_number integer NOT NULL,
  column_name varchar(150),
  error_code varchar(100) NOT NULL,
  error_message text NOT NULL,
  raw_value text,
  raw_row jsonb,
  CONSTRAINT data_import_error_row_number_valid CHECK (row_number > 0)
);

CREATE TABLE data_quality_issue (
  issue_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_type varchar(100) NOT NULL,
  severity varchar(20) NOT NULL,
  table_name varchar(100) NOT NULL,
  record_id varchar(100),
  description text NOT NULL,
  suggested_action text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'OPEN',
  detected_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolved_by uuid,
  import_id uuid REFERENCES data_import(import_id) ON DELETE SET NULL,
  CONSTRAINT data_quality_issue_severity_valid CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  CONSTRAINT data_quality_issue_status_valid CHECK (status IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED')),
  CONSTRAINT data_quality_issue_resolution_valid CHECK (resolved_at IS NULL OR resolved_at >= detected_at)
);

CREATE TABLE audit_log (
  audit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  action varchar(100) NOT NULL,
  entity_type varchar(100) NOT NULL,
  entity_id varchar(100),
  request_id varchar(100),
  ip_hash varchar(128),
  user_agent text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE intelligence_report (
  report_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_type varchar(100) NOT NULL,
  title varchar(250) NOT NULL,
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  generated_by uuid,
  generated_at timestamptz NOT NULL DEFAULT now(),
  model_versions jsonb NOT NULL DEFAULT '[]'::jsonb,
  data_period jsonb NOT NULL DEFAULT '{}'::jsonb,
  review_status varchar(30) NOT NULL DEFAULT 'PENDING_REVIEW',
  report_path text,
  verification_hash varchar(128) NOT NULL UNIQUE,
  CONSTRAINT intelligence_report_review_status_valid CHECK (review_status IN ('PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE copilot_query (
  query_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  question text NOT NULL,
  detected_language varchar(20),
  selected_tool varchar(100),
  tool_parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_text text,
  data_sources jsonb NOT NULL DEFAULT '[]'::jsonb,
  duration_ms integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT copilot_query_duration_valid CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE TABLE source_record_map (
  source_record_map_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system varchar(100) NOT NULL,
  source_record_id varchar(150) NOT NULL,
  entity_type varchar(100) NOT NULL,
  entity_id varchar(150) NOT NULL,
  import_id uuid REFERENCES data_import(import_id) ON DELETE SET NULL,
  mapped_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT source_record_map_unique UNIQUE (source_system, source_record_id, entity_type)
);
