CREATE TABLE user_account (
  user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email citext NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name varchar(200) NOT NULL,
  role_code varchar(50) NOT NULL,
  district_id integer REFERENCES district(district_id),
  unit_id integer REFERENCES police_unit(unit_id),
  clearance_level smallint NOT NULL DEFAULT 1,
  active boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_account_role_valid CHECK (role_code IN ('STATE_ADMIN', 'SCRB_ANALYST', 'DISTRICT_OFFICER', 'STATION_OFFICER', 'INVESTIGATOR', 'EVALUATOR', 'AUDITOR', 'DATA_ENGINEER')),
  CONSTRAINT user_account_clearance_valid CHECK (clearance_level BETWEEN 0 AND 5)
);

CREATE TABLE refresh_token (
  refresh_token_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES user_account(user_id) ON DELETE CASCADE,
  token_hash varchar(128) NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT refresh_token_expiry_valid CHECK (expires_at > created_at)
);

CREATE TABLE role_permission (
  role_code varchar(50) NOT NULL,
  permission_code varchar(100) NOT NULL,
  PRIMARY KEY (role_code, permission_code),
  CONSTRAINT role_permission_role_valid CHECK (role_code IN ('STATE_ADMIN', 'SCRB_ANALYST', 'DISTRICT_OFFICER', 'STATION_OFFICER', 'INVESTIGATOR', 'EVALUATOR', 'AUDITOR', 'DATA_ENGINEER'))
);

CREATE TABLE user_case_assignment (
  user_id uuid NOT NULL REFERENCES user_account(user_id) ON DELETE CASCADE,
  case_master_id bigint NOT NULL REFERENCES case_master(case_master_id) ON DELETE CASCADE,
  assignment_type varchar(50) NOT NULL DEFAULT 'INVESTIGATOR',
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by uuid REFERENCES user_account(user_id),
  PRIMARY KEY (user_id, case_master_id, assignment_type)
);

CREATE TABLE auth_login_attempt (
  login_attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_hash varchar(128) NOT NULL,
  ip_hash varchar(128),
  succeeded boolean NOT NULL,
  attempted_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE person_identity_match
  ADD CONSTRAINT person_identity_match_reviewed_by_fk
  FOREIGN KEY (reviewed_by) REFERENCES user_account(user_id);

ALTER TABLE modus_operandi
  ADD CONSTRAINT modus_operandi_verified_by_fk
  FOREIGN KEY (verified_by) REFERENCES user_account(user_id);

ALTER TABLE alert
  ADD CONSTRAINT alert_reviewed_by_fk
  FOREIGN KEY (reviewed_by) REFERENCES user_account(user_id);

ALTER TABLE alert
  ADD CONSTRAINT alert_assigned_to_fk
  FOREIGN KEY (assigned_to) REFERENCES user_account(user_id);

ALTER TABLE data_import
  ADD CONSTRAINT data_import_uploaded_by_fk
  FOREIGN KEY (uploaded_by) REFERENCES user_account(user_id);

ALTER TABLE data_quality_issue
  ADD CONSTRAINT data_quality_issue_resolved_by_fk
  FOREIGN KEY (resolved_by) REFERENCES user_account(user_id);

ALTER TABLE audit_log
  ADD CONSTRAINT audit_log_user_fk
  FOREIGN KEY (user_id) REFERENCES user_account(user_id);

ALTER TABLE intelligence_report
  ADD CONSTRAINT intelligence_report_generated_by_fk
  FOREIGN KEY (generated_by) REFERENCES user_account(user_id);

ALTER TABLE copilot_query
  ADD CONSTRAINT copilot_query_user_fk
  FOREIGN KEY (user_id) REFERENCES user_account(user_id);
