import axios from 'axios';

const API_BASE = '/api/kavach';

export const kavachApi = {
  getOverview: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/overview`, { params: filters }),
  getDistricts: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/districts`, { params: filters }),
  getDistrict: (district: string, filters?: Record<string, unknown>) => axios.get(`${API_BASE}/districts/${district}`, { params: filters }),
  getMonthlyTrends: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/monthly`, { params: filters }),
  getWeeklyTrends: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/weekly`, { params: filters }),
  getDayOfWeekAnalysis: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/day-of-week`, { params: filters }),
  getHourOfDayAnalysis: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/hour-of-day`, { params: filters }),
  getDaypartAnalysis: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/daypart`, { params: filters }),
  getCategoryGrowth: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/category-growth`, { params: filters }),
  getDistrictComparison: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/district-comparison`, { params: filters }),
  getModusOperandiTrends: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/modus-operandi`, { params: filters }),
  getPeriodComparison: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/trends/period-comparison`, { params: filters }),
  getHotspots: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/hotspots`, { params: filters }),
  getHotspotById: (id: string) => axios.get(`${API_BASE}/hotspots/${id}`),
  getDistrictHotspots: (district: string, filters?: Record<string, unknown>) => axios.get(`${API_BASE}/hotspots/district/${district}`, { params: filters }),
  getAnomalies: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/anomalies`, { params: filters }),
  getNetwork: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/network`, { params: filters }),
  getNetworkForPerson: (personId: string) => axios.get(`${API_BASE}/network/person/${personId}`),
  getNetworkForIncident: (firNumber: string) => axios.get(`${API_BASE}/network/incident/${firNumber}`),
  getNetworkComponents: () => axios.get(`${API_BASE}/network/components`),
  getCrossDistrictNetworks: () => axios.get(`${API_BASE}/network/cross-district`),
  getOffenders: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/offenders`, { params: filters }),
  getOffenderDetail: (offenderId: string) => axios.get(`${API_BASE}/offenders/${offenderId}`),
  getDistrictRisks: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/risk/districts`, { params: filters }),
  getDistrictRisk: (district: string) => axios.get(`${API_BASE}/risk/districts/${district}`),
  getRiskDistribution: () => axios.get(`${API_BASE}/risk/distribution`),
  getCorrelations: () => axios.get(`${API_BASE}/correlations`),
  getCorrelationMatrix: () => axios.get(`${API_BASE}/correlations/matrix`),
  getRankedCorrelations: () => axios.get(`${API_BASE}/correlations/ranked`),
  getAlerts: (filters?: Record<string, unknown>) => axios.get(`${API_BASE}/alerts`, { params: filters }),
  getAlertById: (id: string) => axios.get(`${API_BASE}/alerts/${id}`),
  markAlertReviewed: (id: string) => axios.patch(`${API_BASE}/alerts/${id}/review`),
  copilotQuery: (query: string, filters?: Record<string, unknown>) => axios.post(`${API_BASE}/copilot/query`, { query, filters }),
  getCopilotSuggestions: () => axios.get(`${API_BASE}/copilot/suggestions`),
  generateReport: (filters?: Record<string, unknown>, format?: string) => axios.post(`${API_BASE}/reports`, { filters, format }),
  loadDemoData: () => axios.get(`${API_BASE}/data/load`),
};
